name: Test

on:
  - push
  - pull_request

jobs:

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'

    - name: npm install
      run: npm install

    - name: npm test
      run: npm test

    - name: npm run coveralls
      run: npm run coveralls

    - name: Coveralls publish
      uses: coverallsapp/github-github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}